apps/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('mispesos/', views.mispesos, name="mispesos"),
    path('editpeso/<int:id_peso>',views.editpeso,name='editpeso'),
    path("createpeso/", views.createpeso, name="createpeso"),
    path("objetivos/", views.conobjetivos, name="objetivos")
]

fitporx/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.fit.urls")),
    path('dashboard/',include("apps.dashboard.urls")),
    path('profile/',include('apps.fitprofile.urls'))
]

apps/dashboard/models.py
from django.db import models
from .models.dashboard import Dashboard
# Create your models here.

apps/dashboard/models/dashboard.py
from django.db import models
from django.contrib.auth.models import User

class Dashboard(models.Model):
    fit_fcregister = models.DateField()
    fit_weight = models.FloatField(default=0.0)
    fit_fccrea = models.DateTimeField(auto_now=True)
    fit_user_crea = models.CharField(max_length=100,null=False)
    fit_fc_modi = models.DateTimeField(auto_now=True)
    fit_user_modi = models.CharField(max_length=100,null=True,blank=True)
    fit_estado = models.BooleanField(default=False)
    user = models.ForeignKey(User,related_name='dashboards',on_delete=models.CASCADE)
    fit_observation = models.TextField(max_length=500, null=True,blank=True,default='')
    class Meta:
        ordering = ['-fit_fccrea']
        
    def __str__(self):
        return super().__str__()

apps/dashboard/forms.py
from django.forms import ModelForm
from .models import Dashboard

class PesoForm(ModelForm):
    class Meta:
        model = Dashboard
        fields = ['fit_fcregister','fit_weight','fit_observation']

apps/dashboard/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.db.models import Sum
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Dashboard
from ..fitprofile.models import FitProfile
from datetime import datetime,date,timedelta
from .forms import PesoForm
# Create your views here.
@login_required
def dashboard(request):
    fecha_actual = datetime.now()
    diccionario_fecha = obtener_rango_fecha()
    data = Dashboard.objects.filter(user=request.user,fit_fcregister__gte=diccionario_fecha['fecha_ini'],fit_fcregister__lte=diccionario_fecha['fecha_fin'])
    return render(request,'dashboard/dashboard.html',{
        'data': data,
        'fecha_actual': fecha_actual.date(),
        'pesos':[
            {
                'pesos_dia':obtener_peso_dia(data)
            }
        ]        
    })
def obtener_peso_dia(data):
    pesos ={
        'Monday':0.0,
        'Tuesday':0.0,
        'Wednesday':0.0,
        'Thursday':0.0,
        'Friday':0.0,
        'Saturday':0.0,
        'Sunday':0.0,
    }
    nomb_dia = ''
    for datos in data:
        nomb_dia = datos.fit_fcregister.strftime('%A')
        pesos[nomb_dia] = datos.fit_weight
    return pesos
    
def obtener_rango_fecha():
    fecha_hoy = date.today()
    nombre_dia = fecha_hoy.strftime('%A')
    fecha_ini = fecha_hoy
    fecha_fin = fecha_ini
    dias_resta = 0
    diccionario_fecha ={}
    match nombre_dia:
        case "Monday":
            dias_resta = 0
        case "Tuesday":
            dias_resta = 1
        case "Wednesday":
            dias_resta = 2
        case "Thursday":
            dias_resta = 3
        case "Friday":
            dias_resta = 4
        case "Saturday":
            dias_resta = 5
        case "Sunday":
            dias_resta = 6
        case _:
            dias_resta = 0
    fecha_ini = fecha_hoy - timedelta(days=dias_resta)
    fecha_fin = fecha_ini + timedelta(days=6)
    diccionario_fecha = {
        'fecha_ini': fecha_ini,
        'fecha_fin': fecha_fin
    }
    return diccionario_fecha
@login_required
def mispesos(request):
    user = request.user
    data = Dashboard.objects.filter(user=user)
    return render(request,'dashboard/consultapesos.html',{
        'consultapesos': data
    })

@login_required
def editpeso(request,id_peso):
    pesos = get_object_or_404(Dashboard,pk=id_peso)
    if request.method == 'GET':
        editform = PesoForm(instance=pesos)
    else:
        editform = PesoForm(request.POST,instance=pesos)
        if editform.is_valid():
            editform.save()
            messages.success(request,"Registro actualizado correctamente")
            return redirect('mispesos')
    return render(request,'dashboard/editpesos.html',{
        'formedit': editform,
        'pesos':pesos
    })

@login_required
def createpeso(request):
    if request.method == 'POST':
        #validacion para que no exista registro de dos pesos en una misma fecha
        frmcreate = PesoForm(request.POST)
        #buscando datos
        dato = Dashboard.objects.filter(user=request.user,fit_fcregister=request.POST['fit_fcregister'])
        if dato:
            messages.info(request,"Ya existe un peso en esta fecha")
            return redirect('createpeso')
        if frmcreate.is_valid():
            dashboard = frmcreate.save(commit=False)#aun no me guarda
            dashboard.user = request.user
            frmcreate.fit_user_crea = request.user.username
            frmcreate.save()
            messages.success(request,"Se creo un nuevo peso")
            return redirect('mispesos')
    else:
        frmcreate = PesoForm()
        
    return render(request,'dashboard/createpeso.html',{
        'frmcreate': frmcreate
    })
def calcula_edad(fecha):
    edad = 0
    year_now = datetime.today()
    edad = year_now.year - fecha.year
    return edad

def calcular_calorias(peso, genero):
    #dato por harry venedict
    CALORIAS_GENERO = {
        'M': 35,
        'F': 33,
    }
    if peso is None or genero not in CALORIAS_GENERO:
        return None
    mantenimiento = peso * CALORIAS_GENERO[genero]
    calorias_extra = mantenimiento * 0.2
    return {
        'mantenimiento': round(mantenimiento),
        'deficit': round(mantenimiento - calorias_extra),
        'superavit': round(mantenimiento + calorias_extra)
    }
def calcular_promedio_semanal(request,peso):
    fc_ini_fin = obtener_rango_fecha()
    users = request.user
    semana = 7
    sumpeso = 0
    if peso is None:
        return None
    dato = Dashboard.objects.filter(user=users,fit_fcregister__gte=fc_ini_fin['fecha_ini'],fit_fcregister__lte=fc_ini_fin['fecha_fin']).aggregate(total=Sum('fit_weight'))
    promedio = round((dato['total'] / semana),2)
    return promedio
@login_required
def conobjetivos(request):
    #obtenemos el perfil
    edad = None
    peso_perdido = 0.0
    calorias = 0.0
    peso_semanal = 0.0
    data_profile = get_object_or_404(FitProfile,user=request.user)
    if data_profile.fit_prof_birth_date:
        edad = calcula_edad(data_profile.fit_prof_birth_date)
    if data_profile.fit_prof_weight:
        calorias = calcular_calorias(data_profile.fit_prof_weight,data_profile.fit_sexo)
        #el peso semana y el peso perdido solo se calculara automaticamente cuando el dia sea domingo
        fecha_hoy = date.today()
        nombre_dia = fecha_hoy.strftime('%A')
        if fecha_hoy == 'Sunday':               
            peso_semanal = calcular_promedio_semanal(request,data_profile.fit_prof_weight)
            peso_perdido = round(data_profile.fit_prof_weight - peso_semanal,2)
    return render(request,'dashboard/objetivos.html',{
        'data_profile': data_profile,
        'edad': edad,
        'calorias': calorias,
        'peso_semanal':peso_semanal,
        'peso_perdido': peso_perdido
    })

apps/dashboard/templates/dashboard/consultapesos.html
{% extends "basetablero.html" %}
{% load static %}
{% block title_tablero %}
    Consulta tus Pesos
{% endblock title_tablero %}

{% block style_tablero %}
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">        
{% endblock style_tablero %}

{% block username_tablero %}
    {{request.user}}
{% endblock username_tablero %}
    
{% block subtitle_tablero %}
    Consulta de Pesos
{% endblock subtitle_tablero %}

{% block content_tablero %}
<div class="card shadow mb-4">
    {% if messages %}
        {% for mensaje in messages %}
            <div class="alert alert-success" role="alert">
                {{mensaje}}
            </div>
        {% endfor %}
    {% endif %}
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Mis Pesos</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Fecha de Pesos</th>
                        <th>Dia</th>
                        <th>Peso</th>
                        <th>Observacion</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for peso in consultapesos %}
                        <tr>
                            <td>{{peso.fit_fcregister|date:"d/m/Y"}}</td>
                            <td>{{peso.fit_fcregister|date:"l"}}</td>
                            <td>{{peso.fit_weight}}</td>
                            <td>{{peso.fit_observation|default:"Sin Observaciones"}}</td>
                            <td>
                                <a href="{% url 'editpeso' peso.id%}" class="text-decoration-none">
                                    <i class="fas fa-edit"></i>
                                    Editar
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content_tablero %}

{% block scripts_tablero %}
    <script src="{% static 'js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static 'js/dataTables.bootstrap4.min.js'%}"></script>
    <script src="{% static 'js/datatables-demo.js'%}"></script>
{% endblock scripts_tablero %}

apps/dashboard/templates/dashboard/createpeso.html
{% extends 'basetablero.html' %}

{% block title_tablero %}
    Nuevo Registro
{% endblock title_tablero %}

{% block username_tablero %}
    {{request.user}}
{% endblock username_tablero %}
    
{% block subtitle_tablero %}
    Nuevo Peso
{% endblock subtitle_tablero %}

{% block content_tablero %}
    <main class="container">
        <form action="{%url 'createpeso'%}" method="POST" class="row g-3">    
            {% csrf_token %}
            {% if messages %}
                {% for mensaje in messages %}
                    <div class="alert alert-success" role="alert">
                        {{mensaje}}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-12 mb-3">
                    <label for="id_fit_fcregister" class="form-label">Fecha de Registro</label>
                    <input type="date" id="id_fit_fcregister" class="form-control" name="fit_fcregister">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_fit_weight" class="form-label">Peso en Kg</label>
                    <input type="number" step="0.01" id="id_fit_weight" name="fit_weight" class="form-control">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_fit_observation" class="form-label">Observaciones</label>
                    <textarea type="text" id="id_fit_observation" name="fit_observation" class="form-control"></textarea>
                </div>
                <div class="col-12 mb-3">
                    <button class="btn btn-success">
                        Registrar
                    </button>
                </div>
            </div>
        </form>               
       
    </main>
{% endblock content_tablero %}
    
        

apps/dashboard/templates/dashboard/dashboard.html
{% extends 'basetablero.html' %}

{% block title_tablero %}
    Tablero Pesos
{% endblock title_tablero %}

{% block username_tablero %}
    {{request.user}}
{% endblock username_tablero %}
    
{% block subtitle_tablero %}
    Mis Pesos
{% endblock subtitle_tablero %}
    

{% block content_tablero %}

   
    <main class="container">
        <!-- Area Chart -->
        <div class="col-md-10 mt-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Tablero del Dia {{fecha_actual|date:"d/m/Y"}}</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">Lunes</th>
                            <th scope="col">Martes</th>
                            <th scope="col">Miercoles</th>
                            <th scope="col">Jueves</th>
                            <th scope="col">Viernes</th>
                            <th scope="col">Sabado</th>
                            <th scope="col">Domingo</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            
                            {% for data_tablero in pesos %}
                                <tr>
                                    <th scope="row">{{forloop.counter}}</th>
                                    <td>{{ data_tablero.pesos_dia.Monday }}</td>
                                    <td>{{ data_tablero.pesos_dia.Tuesday }}</td>
                                    <td>{{ data_tablero.pesos_dia.Wednesday }}</td>
                                    <td>{{ data_tablero.pesos_dia.Thursday }}</td>
                                    <td>{{ data_tablero.pesos_dia.Friday }}</td>
                                    <td>{{ data_tablero.pesos_dia.Saturday }}</td>
                                    <td>{{ data_tablero.pesos_dia.Sunday }}</td>                               
                                </tr>
                            {%empty%}
                            <tr>
                                <td collspan="7">Aun no tiene registros esta semana</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </main>    
 

{% endblock content_tablero %}
        

apps/dashboard/templates/dashboard/editpesos.html
{% extends "basetablero.html" %}

{% block title_tablero %}
    Editar Mi Peso
{% endblock title_tablero %}

{% block username_tablero %}
    {{request.user}}
{% endblock username_tablero %}
    
{% block subtitle_tablero %}
    Editar Registro
{% endblock subtitle_tablero %}

{% block content_tablero %}

<main class="container">
    
    <form method="POST" class="row g-3">
        {% csrf_token %}
        <div class ="row">
            <div class="col-12 mb-3">
                <label for="id_fit_fcregister" class="form-label">Fecha de Registro</label>
                <input type="date" id="id_fit_fcregister" class="form-control" name="fit_fcregister" value="{{pesos.fit_fcregister|date:'Y-m-d'}}">
            </div>
            <div class="col-12 mb-3">
                <label for="id_fit_weight" class="form-label">Peso en Kg</label>
                <input type="number" step="0.1" id="id_fit_weight" class="form-control" name="fit_weight" value="{{pesos.fit_weight}}">
            </div>
            <div class="col-12 mb-3">
                <label for="id_fit_observation" class="form-label">Observaciones</label>
                <textarea name="fit_observation" id="id_fit_observation" class="form-control">{{pesos.fit_observation}}</textarea>
            </div>
            <div class="col-12 mb-3">
                <button class="btn btn-success">
                    Guardar
                </button>
            </div>
        </div>
    </form>
</main>
{% endblock content_tablero %}
    

apps/dashboard/templates/dashboard/objetivos.html
{% extends 'basetablero.html' %}

{% block title_tablero %}
    Mis Objetivos
{% endblock title_tablero %}

{% block username_tablero %}
    {{request.user}}
{% endblock username_tablero %}
    
{% block subtitle_tablero %}
    Mis Objetivos
{% endblock subtitle_tablero %}

{% block content_tablero %}
<div class="row">
    <div class="col-lg-6">
        <!-- Dropdown Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Objetivos Caloricos</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                        aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <table class="table">
                    
                    <tbody>
                        <tr>
                            <th>
                                Fecha de Nacimiento:
                            </th>
                            <th>{{data_profile.fit_prof_birth_date|date:"d/m/Y"|default:"No tiene fecha de nacimiento"}}</th>
                        </tr>
                        <tr>
                            <th>Edad</th>
                            <th>
                                {{edad|default:"No tiene fecha de nacimiento"}}
                            </th>
                        </tr>
                        <tr>
                            <th>Peso Perfil</th>
                            <th>{{data_profile.fit_prof_weight|default:"No tiene peso en su Perfil"}}</th>
                        </tr>
                        <tr>
                            <th>Altura Perfil</th>
                            <th>{{data_profile.fit_prof_height|default:"No tiene altura en su Perfil"}}</th>
                        </tr>
                        <tr>
                            <th>Calorias de Mantenimiento</th>
                            <th>{{calorias.mantenimiento|default:"No tiene peso en su Perfil"}}</th>
                        </tr>
                        <tr>
                            <th>Calorias de Deficit</th>
                            <th>{{calorias.deficit|default:"No tiene peso en su perfil"}}</th>
                        </tr>
                        <tr>
                            <th>Calorias de Superavit</th>
                            <th>{{calorias.superavit|default:"No tiene peso en su perfil"}}</th>
                        </tr>
                    </tbody>
                </table>
                
            </div>
        </div>
    </div>

    <div class="col-lg-6">

        <!-- Dropdown Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Peso promedio en DEFICIT</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                        aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Peso Perfil</th>
                            <th>{{data_profile.fit_prof_weight}}</th>
                        </tr>
                        <tr>
                            <th>Peso promedio Semanal</th>
                            <th>{{peso_semanal}}</th>
                        </tr>
                        <tr>
                            <th>Peso Perdido</th>
                            <th>{{peso_perdido}}</th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
{% endblock content_tablero %}
            