apps/fitprofile/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.fitprofiles,name='fitprofiles')    
]

fitporx/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.fit.urls")),
    path('dashboard/',include("apps.dashboard.urls")),
    path('profile/',include('apps.fitprofile.urls'))
]

apps/fitprofile/models.py
from django.db import models
from .models import FitProfile
# Create your models here.

apps/fitprofile/models/fitprofile.py
from django.db import models
from django.contrib.auth.models import User
class FitProfile(models.Model):
    class Genero(models.TextChoices):
        VACIO = '', 'Selecciones un genero'
        MASCULINO = 'M','Hombre'
        FEMENINO = 'F', 'Mujer'
    
    fit_prof_phne = models.CharField(max_length=20,blank=True,null=True,default='')
    fit_prof_birth_date = models.DateField(null=True,blank=True)
    fit_prof_avatar = models.CharField(max_length=200,blank=True,null=True,default='')
    fit_prof_fc_crea = models.DateTimeField(auto_now_add=True)
    fit_prof_fc_modi = models.DateTimeField(auto_now=True)
    fit_prof_height = models.PositiveBigIntegerField(default=0)
    fit_prof_weight = models.FloatField(default=0.0)
    fit_sexo = models.CharField(max_length=1,choices=Genero.choices,blank=True,null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='fitprofiles')
    
    class Meta:
        ordering = ['-fit_prof_fc_crea']
        unique_together = ('fit_prof_phne',)
    def __str__(self):
        return super().__str__()
    
  

apps/fitprofile/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import FitProfile
from django import forms

class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']
        

class ProfileForm(ModelForm):
    class Meta:
       
        model = FitProfile
        fields = ['fit_prof_phne','fit_prof_birth_date','fit_prof_height','fit_prof_weight','fit_sexo']
  

apps/fitprofile/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import FitProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm,ProfileForm
from django.contrib import messages
# Create your views here.
@login_required
def fitprofiles(request):
    user = request.user
    profile = get_object_or_404(FitProfile,user=request.user)
    if request.method == 'GET':
        frm_user = UserUpdateForm(instance=user)
        frm_profile = ProfileForm(instance=profile)
    else:        
        frm_user = UserUpdateForm(request.POST,instance=user)
        frm_profile = ProfileForm(request.POST,instance=profile)
        profile_s = FitProfile.objects.filter(fit_prof_phne=request.POST['fit_prof_phne'])
     
        if profile.fit_prof_phne and (profile.user != request.user):
            messages.warning(request,"El telefono que intenta registrar ya esta en uso")
            return redirect('fitprofiles')
        if frm_user.is_valid() and frm_profile.is_valid():
            print('request.POST')
            frm_user.save()
            frm_profile.save()
            messages.success(request,'Perfil actualizado corretamente')
            return redirect('fitprofiles')
    
    return render(request,'fitprofile/profile.html',{
        'frmuser': frm_user,
        'frmprofile': frm_profile,
        'genero': frm_profile.fields['fit_sexo'].choices
    })
 

apps/fitprofile/templates/fitprofile/profile.html
{% extends 'basetablero.html' %}

{% block title_tablero %}
    Profile
{% endblock title_tablero %}

{% block username_tablero %}
    {{request.user}}
{% endblock username_tablero %}
    
{% block subtitle_tablero %}
    Mi Perfil
{% endblock subtitle_tablero %}

{% block content_tablero %}

    <main class="container">
        <form action="{%url 'fitprofiles'%}" method="POST" class="row g-3">
        
            {% if messages %}
                {% for mensaje in messages %}
                    <div class="alert alert-{{ mensaje.tags }}" role="alert">
                        {{mensaje}}
                    </div>
                {% endfor %}
            {% endif %}
                
            {% csrf_token %}
            <div class="row">
                <div class="col-12 mb-3">
                    <label for="id_first_name" class="form-label">Nombre</label>
                    <input type="text" id="id_first_name" class="form-control" name="first_name" value="{{frmuser.first_name.value}}">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_last_name" class="form-label">Apellido</label>
                    <input type="text" id="id_last_name" name="last_name" class="form-control" value="{{frmuser.last_name.value}}">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    <input type="text" id="id_email" name="email" class="form-control" value="{{frmuser.email.value}}">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_fit_prof_phne" class="form-label">Telefono</label>
                    <input type="text" id="id_fit_prof_phne" name="fit_prof_phne" class="form-control" value="{{frmprofile.fit_prof_phne.value}}">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_fit_prof_birth_date" class="form-label">Fecha de Nacimiento</label>
                    <input type="date" id="id_fit_prof_birth_date" name="fit_prof_birth_date" class="form-control" value="{{frmprofile.fit_prof_birth_date.value|date:'Y-m-d'}}">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_fit_prof_height" class="form-label">Altura en centimetros</label>
                    <input type="number" id="id_fit_prof_height" name="fit_prof_height" class="form-control" value="{{frmprofile.fit_prof_height.value}}">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_fit_prof_weight" class="form-label">Peso en Kg</label>
                    <input type="number" step="0.01" id="id_fit_prof_weight" name="fit_prof_weight" class="form-control" value="{{frmprofile.fit_prof_weight.value}}">
                </div>
                <div class="col-12 mb-3">
                    <label for="id_fit_sexo" class="form-label">Genero</label>
                    <select class="form-control" name="fit_sexo" id="id_fit_sexo" value="{{frmprofile.fit_sexo.value}}">
                        {% for valor,descripcion in genero %}
                            <option value="{{ valor }}"
                                {% if frmprofile.fit_sexo.value == valor %}
                                    selected
                                {% endif %}>
                                
                                {{ descripcion }}
                            </option>
                        {% endfor %}
                        
                    </select>
                    
                </div>
            </div>
        
            <button class="btn btn-success">
                Guardar
            </button>
        </form>                    
    </main>
  

        
 
   
{% endblock content_tablero %}
    